FROM node:8

WORKDIR /usr/src/app

####debug######
# install vim
RUN apt-get update \
    && apt-get install -y \
        vim

# Install app dependencies
RUN npm install -g nodemon
######debug#######


COPY package*.json ./

RUN npm install

COPY . ./

EXPOSE 4017

CMD ["npm" ,"run", "server"]
