FROM node:8

WORKDIR /usr/src/app
####debug######
# install vim
RUN apt-get update \
    && apt-get install -y \
        vim

# Install app dependencies
RUN npm install -g nodemon
######debug#######
ENV API_HOST pom-hackathon_pom-vpn-server:4017

COPY package*.json ./

RUN npm install

COPY . ./

EXPOSE 3005

CMD ["npm","run" , "client"]
